language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dthunn/docker-travis-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dthunn/docker-travis-react npm run test -- --coverage
